# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "stellar"
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Costan"]
  s.date = "2012-11-16"
  s.description = "So we don't have to put up with Stellar's craptastic ui"
  s.email = "victor@costan.us"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".project",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/stellar.rb",
    "lib/stellar/auth.rb",
    "lib/stellar/client.rb",
    "lib/stellar/courses.rb",
    "lib/stellar/gradebook.rb",
    "lib/stellar/homework.rb",
    "lib/stellar/members.rb",
    "lib/stellar/mitca.crt",
    "spec/fixtures/.gitkeep",
    "spec/spec_helper.rb",
    "spec/stellar/auth_spec.rb",
    "spec/stellar/client_spec.rb",
    "spec/stellar/courses_spec.rb",
    "spec/stellar/gradebook_spec.rb",
    "spec/stellar/gradebook_student_spec.rb",
    "spec/stellar/homework_spec.rb",
    "spec/stellar/homework_submissions_spec.rb",
    "spec/stellar/members_spec.rb",
    "spec/stellar_spec.rb",
    "spec/support/test-credentials.rb",
    "stellar.gemspec"
  ]
  s.homepage = "http://github.com/pwnall/stellar"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Automated access to MIT's Stellar data"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mechanize>, [">= 2.5.1"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.5.5"])
      s.add_development_dependency(%q<bundler>, [">= 1.2.1"])
      s.add_development_dependency(%q<debugger>, [">= 0"])
      s.add_development_dependency(%q<highline>, [">= 1.6.15"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_development_dependency(%q<rspec>, [">= 2.6.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0.7.1"])
      s.add_development_dependency(%q<yard>, [">= 0.8.3"])
      s.add_development_dependency(%q<yard-rspec>, [">= 0.1"])
      s.add_development_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<mechanize>, [">= 2.5.1"])
      s.add_dependency(%q<nokogiri>, [">= 1.5.5"])
      s.add_dependency(%q<bundler>, [">= 1.2.1"])
      s.add_dependency(%q<debugger>, [">= 0"])
      s.add_dependency(%q<highline>, [">= 1.6.15"])
      s.add_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_dependency(%q<rspec>, [">= 2.6.0"])
      s.add_dependency(%q<simplecov>, [">= 0.7.1"])
      s.add_dependency(%q<yard>, [">= 0.8.3"])
      s.add_dependency(%q<yard-rspec>, [">= 0.1"])
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<mechanize>, [">= 2.5.1"])
    s.add_dependency(%q<nokogiri>, [">= 1.5.5"])
    s.add_dependency(%q<bundler>, [">= 1.2.1"])
    s.add_dependency(%q<debugger>, [">= 0"])
    s.add_dependency(%q<highline>, [">= 1.6.15"])
    s.add_dependency(%q<jeweler>, [">= 1.8.4"])
    s.add_dependency(%q<rspec>, [">= 2.6.0"])
    s.add_dependency(%q<simplecov>, [">= 0.7.1"])
    s.add_dependency(%q<yard>, [">= 0.8.3"])
    s.add_dependency(%q<yard-rspec>, [">= 0.1"])
    s.add_dependency(%q<json>, [">= 0"])
  end
end

